// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace IL.MT
{
	public partial class ImagesListCell : UITableViewCell
	{
		public ImagesListCell (IntPtr handle) : base (handle)
		{
		}
	}
}
